# Files and directories
data-directory: data
pairings-directory: pairings
values-directory: values

# Name for where to store the full dataset
full-dataset: full.json

# URLs - right now, we only use the `live` one
urls:
  live: https://docs.google.com/spreadsheets/d/e/2PACX-1vT0E0Y7txIa2pfBuusA1cd8X5OVhQ_D0qZC8D40KhTU3xB7McsPR2kuB7GH6ncmNT3nfjEYGbscOPp0/pub?gid=2042982575&single=true&output=csv

# Columns to clear out in clean dataset
skip-columns:
  - Source
  - Imported from former archive
  - Search (fulton)
  - Search (newspapers.com)
  - EIMA_Search

# Here are the pairings that will be generated. Add to it if you want to create other datafiles.
pairings:
  - [Normalized City, Normalized performer]
  - [Normalized performer, Normalized City]
  - [Year, Normalized City]
  - [Unsure whether drag artist, Normalized performer]
  - [Normalized performer, Normalized Venue]
  - [Normalized Venue, Normalized performer]
  - [Source clean, Normalized performer]
  - [Normalized performer, Newspaper_ID]
  - [Normalized performer, EIMA_ID]
  - [Normalized performer, "Comment on node: performer"]
  - [Normalized Venue, "Comment on node: venue"]
  - [Normalized City, "Comment on node: city"]
  - [Normalized Revue Name, "Comment on edge: revue"]
  - [Newspaper, Normalized performer]
  - [Normalized Revue Name, Normalized performer]
  - [Has image, Normalized performer]
