name: Sync data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version:
          - 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Deploy EIMA clippings
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: df6bc187b76e128d310733c614c1c968
          gist_file_name: eima_clippings.json
          file_path: ./data/eima_clippings.json
      - name: Deploy Newspapers.com clippings
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 451bc78066ac6f191e9e1c4421163587
          gist_file_name: newspapers.com_clippings.json
          file_path: ./data/newspapers.com_clippings.json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Synchronize data
        run: |
          python sync-data.py
      - name: Deploy full dataset
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: c9febb0a218a9b00b3fad714a49c0e4f
          gist_file_name: full-drag-dataset.json
          file_path: ./data/full.json
      - name: Deploy pairings dataset
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 71da192b279f98d8807d8c9b0dc12421
          gist_file_name: full-pairings-dataset.json
          file_path: ./data/pairings/full.json
      - name: Deploy values dataset
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 5143facd5b6e41d8a68a916f2a45a3f9
          gist_file_name: full-values-dataset.json
          file_path: ./data/values/full.json
      - name: Deploy full network dataset
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 6f52cb9adfb7d503dabdbf14a2b49247
          gist_file_name: full-network-dataset.json
          file_path: ./data/network/full.json
      # - name: Deploy ego network dataset
      #  uses: exuanbo/actions-deploy-gist@v1
      #  with:
      #    token: ${{ secrets.TOKEN }}
      #    gist_id: 2b3d520976e5e251b75db09b4b13ad48
      #    gist_file_name: ego-networks-14-days-no-unnamed.json
      #    file_path: ./data/network/live/ego-networks-14-days-no-unnamed.json
      - name: Deploy 3-day network dataset
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 4e77f1c731f8100ddfaa3692fc0feb0d
          gist_file_name: live-co-occurrence-grouped-by-3-days-no-unnamed-performers.json
          file_path: ./data/network/live/live-co-occurrence-grouped-by-3-days-no-unnamed-performers.json
      - name: Deploy 14-day network dataset
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: fd3d7baa63410db5ed73d25b2f0d8086
          gist_file_name: live-co-occurrence-grouped-by-14-days-no-unnamed-performers.json
          file_path: ./data/network/live/live-co-occurrence-grouped-by-14-days-no-unnamed-performers.json

      # - name: Commit updates
      #  run: |
      #    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #    git config --local user.name "github-actions[bot]"
      #    git checkout -B published
      #    git add -f data
      #    git commit -m "Updated data"
      #    git push -f origin published
